@startuml

title __MODEL's Class Diagram__\n

  namespace ru.training.karaf.model {
    interface ru.training.karaf.model.Capability {
        {abstract} + getAccuracy()
        {abstract} + getRange()
        {abstract} + getResolution()
    }
  }
  

  namespace ru.training.karaf.model {
    interface ru.training.karaf.model.ClimateParameter {
        {abstract} + getSensorTypes()
        {abstract} + getUnits()
    }
  }
  

  namespace ru.training.karaf.model {
    interface ru.training.karaf.model.Entity {
        {abstract} + getId()
        {abstract} + getName()
    }
  }
  

  namespace ru.training.karaf.model {
    interface ru.training.karaf.model.Location {
        {abstract} + getId()
        {abstract} + getName()
    }
  }
  

  namespace ru.training.karaf.model {
    interface ru.training.karaf.model.Measuring {
        {abstract} + getTimestamp()
        {abstract} + getValue()
    }
  }
  

  namespace ru.training.karaf.model {
    interface ru.training.karaf.model.Sensor {
        {abstract} + getLocation()
        {abstract} + getType()
        {abstract} + getUsers()
    }
  }
  

  namespace ru.training.karaf.model {
    interface ru.training.karaf.model.SensorType {
        {abstract} + getCapability()
        {abstract} + getMinTime()
        {abstract} + getParameters()
        {abstract} + getSensors()
    }
  }
  

  namespace ru.training.karaf.model {
    interface ru.training.karaf.model.UniqueFieldEntity {
    }
  }
  

  namespace ru.training.karaf.model {
    interface ru.training.karaf.model.Unit {
        {abstract} + getClimateParameters()
        {abstract} + getNotation()
    }
  }
  

  namespace ru.training.karaf.model {
    interface ru.training.karaf.model.User {
        {abstract} + getLogin()
        {abstract} + getProperties()
        {abstract} + getSensors()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
