@startuml

title __REST's Class Diagram__\n

  namespace ru.training.karaf.rest {
    interface ru.training.karaf.rest.ClimateParameterRestService {
        {abstract} + addUnits()
        {abstract} + create()
        {abstract} + delete()
        {abstract} + get()
        {abstract} + getAll()
        {abstract} + getByName()
        {abstract} + update()
    }
  }
  

  namespace ru.training.karaf.rest {
    interface ru.training.karaf.rest.LocationRestService {
        {abstract} + create()
        {abstract} + delete()
        {abstract} + get()
        {abstract} + getAll()
        {abstract} + update()
    }
  }
  

  namespace ru.training.karaf.rest {
    interface ru.training.karaf.rest.SensorRestService {
        {abstract} + addUsers()
        {abstract} + create()
        {abstract} + delete()
        {abstract} + get()
        {abstract} + getAll()
        {abstract} + setLocation()
        {abstract} + setSensorType()
        {abstract} + update()
    }
  }
  

  namespace ru.training.karaf.rest {
    interface ru.training.karaf.rest.SensorTypeRestService {
        {abstract} + addParameters()
        {abstract} + create()
        {abstract} + delete()
        {abstract} + get()
        {abstract} + getAll()
        {abstract} + update()
    }
  }
  

  namespace ru.training.karaf.rest {
    interface ru.training.karaf.rest.UnitRestService {
        {abstract} + create()
        {abstract} + delete()
        {abstract} + get()
        {abstract} + getAll()
        {abstract} + update()
    }
  }
  

  namespace ru.training.karaf.rest {
    interface ru.training.karaf.rest.UserRestService {
        {abstract} + create()
        {abstract} + delete()
        {abstract} + get()
        {abstract} + getAll()
        {abstract} + update()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
