@startuml

title __MODEL-API's Class Diagram__\n

  namespace ru.training.karaf.model {
    interface ru.training.karaf.model.Capability {
    }
  }
  

  namespace ru.training.karaf.model {
    interface ru.training.karaf.model.ClimateParameter {
    }
  }
  

  namespace ru.training.karaf.model {
    interface ru.training.karaf.model.Entity {
    }
  }
  

  namespace ru.training.karaf.model {
    interface ru.training.karaf.model.Location {
    }
  }
  

  namespace ru.training.karaf.model {
    interface ru.training.karaf.model.Measuring {
    }
  }
  

  namespace ru.training.karaf.model {
    interface ru.training.karaf.model.Sensor {
    }
  }
  

  namespace ru.training.karaf.model {
    interface ru.training.karaf.model.SensorType {
    }
  }
  

  namespace ru.training.karaf.model {
    interface ru.training.karaf.model.UniqueFieldEntity {
    }
  }
  

  namespace ru.training.karaf.model {
    interface ru.training.karaf.model.Unit {
    }
  }
  

  namespace ru.training.karaf.model {
    interface ru.training.karaf.model.User {
    }
  }
  

  namespace ru.training.karaf.repo {
    interface ru.training.karaf.repo.ClimateParameterRepo {
    }
  }
  

  namespace ru.training.karaf.repo {
    interface ru.training.karaf.repo.LocationRepo {
    }
  }
  

  namespace ru.training.karaf.repo {
    interface ru.training.karaf.repo.Repo {
    }
  }
  

  namespace ru.training.karaf.repo {
    interface ru.training.karaf.repo.SensorRepo {
    }
  }
  

  namespace ru.training.karaf.repo {
    interface ru.training.karaf.repo.SensorTypeRepo {
    }
  }
  

  namespace ru.training.karaf.repo {
    interface ru.training.karaf.repo.UniqueValidationRepo {
    }
  }
  

  namespace ru.training.karaf.repo {
    interface ru.training.karaf.repo.UnitRepo {
    }
  }
  

  namespace ru.training.karaf.repo {
    interface ru.training.karaf.repo.UserRepo {
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
